.Step 1: Checkout the repository from GitHub

[source, bash]
----
git clone https://github.com/opennms-config-modules/smartctl
----

.Step 2: Allow SNMP agent to run wrapper scripts with sudo

The Net-SNMP agents runs as unprivileged user `snmp` and isn't allowed to run `smartctl`.
With creating a `sudoers` file it is possible to let `snmp` just run the necessary commands with sudo instead of running the whole Net-SNMP agent with root privileges.

[source, bash]
----
cp snmp-extend/snmp_storcli /etc/sudoers.d/snmp_smartctl
----

.Step 3: Copy to wrapper scripts to your server

The wrapper scripts from this repository can be copied to `/usr/local/bin`.

[source, bash]
----
cp snmp-extend/check_smart_disk.sh /usr/local/bin
----

NOTE: You can use any other location, just make sure the extend commands and the sudoers file match your path.

.Step 4: Extend the Net-SNMP agent to run the scripts in /etc/snmpd.conf with

[source, bash]
----
extend smart_health /bin/bash -c 'sudo /usr/local/bin/check_smart_disk_raid.sh'
----

To enable the extend directive, the SNMP agent needs to be restarted with

[source, bash]
----
systemctl restart snmpd
----

Test if you can request the OID from your monitoring server with:

[source, bash]
----
snmpwalk -v 2c -c <your-community> <your-server> .1.3.6.1.4.1.8072.1.3.2.4.1.2.9.115.109.97.114.116.68.105.115.107.1
----

.Step 5: Add SNMP monitors in Pollerd to test extended scripts in poller-configuration.xml

Create a SNMP monitor in Pollerd with the following configuration parameters:

[source, xml]
----
<service name="SMART-Health" interval="43200000" user-defined="true" status="on">
    <parameter key="oid" value=".1.3.6.1.4.1.8072.1.3.2.4.1.2.9.115.109.97.114.116.68.105.115.107.1"/>
    <parameter key="retry" value="1"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="operator" value="="/>
    <parameter key="operand" value="0"/>
</service>

<monitor service="SMART-Health" class-name="org.opennms.netmgt.poller.monitors.SnmpMonitor"/>
----

To enable the services, you have to restart OpenNMS.
When OpenNMS is restarted assign the service _SMART-Health_ to an SNMP enabled IP interface of your Node in OpenNMS or use an SNMP detector for the given OIDS.
